import { ShowcaseApp } from './ShowcaseApp';
import { LoadingComponent, TooltipComponent } from '@qimenjs/component-core';
import '@/theme/light.css';
import '@/theme/skeleton.css';
import '@/theme/layout.css';
import '@/theme/utility.css';
import './showcase.css';
import { Button } from './Button';
import { SimpleButton } from './SimpleButton';
import { DialogTest, PopoverTest, IndicatorTest } from './FloatsTest';
const app = document.getElementById('app')!;
const shell = new ShowcaseApp();
app.appendChild(shell.el);
const dialogTest = new DialogTest();
shell.el.appendChild(dialogTest.el);
const popoverTest = new PopoverTest();
shell.el.appendChild(popoverTest.el);
const indicatorTest = new IndicatorTest();
shell.el.appendChild(indicatorTest.el);
