import { ShowcaseApp } from './ShowcaseApp';
import { LoadingComponent, TooltipComponent } from '@qimenjs/component-core';
import '@/theme/light.css';
import '@/theme/skeleton.css';
import '@/theme/layout.css';
import '@/theme/utility.css';
import './showcase.css';
import { Button } from './Button';
import { OverlayTest } from './FixesTest';
const app = document.getElementById('app')!;
const shell = new ShowcaseApp();
app.appendChild(shell.el);
const overlayTest = new OverlayTest();
shell.appendChild(overlayTest.el);
