export declare const ValidationErrorCode: {
    readonly REQUIRED: "VALIDATION_REQUIRED";
    readonly TYPE_MISMATCH: "VALIDATION_TYPE_MISMATCH";
    readonly INVALID_VALUE: "VALIDATION_INVALID_VALUE";
    readonly TOO_SMALL: "VALIDATION_TOO_SMALL";
    readonly TOO_LARGE: "VALIDATION_TOO_LARGE";
    readonly OUT_OF_RANGE: "VALIDATION_OUT_OF_RANGE";
    readonly INVALID_FORMAT: "VALIDATION_INVALID_FORMAT";
    readonly PATTERN_MISMATCH: "VALIDATION_PATTERN_MISMATCH";
    readonly NOT_ALLOWED: "VALIDATION_NOT_ALLOWED";
    readonly MISSING_FIELD: "VALIDATION_MISSING_FIELD";
    readonly DUPLICATE: "VALIDATION_DUPLICATE";
    readonly CONDITION_FAILED: "VALIDATION_CONDITION_FAILED";
    readonly CUSTOM: "VALIDATION_CUSTOM";
    readonly PASSWORD_TOO_SHORT: "VALIDATION_PASSWORD_TOO_SHORT";
    readonly PASSWORD_MISSING_UPPERCASE: "VALIDATION_PASSWORD_MISSING_UPPERCASE";
    readonly PASSWORD_MISSING_LOWERCASE: "VALIDATION_PASSWORD_MISSING_LOWERCASE";
    readonly PASSWORD_MISSING_DIGIT: "VALIDATION_PASSWORD_MISSING_DIGIT";
    readonly PASSWORD_MISSING_SPECIAL: "VALIDATION_PASSWORD_MISSING_SPECIAL";
};
export type ValidationErrorCode = typeof ValidationErrorCode[keyof typeof ValidationErrorCode];
//# sourceMappingURL=codes.d.ts.map