// @presets/archive.ts
import { MimeTypeRegistrar } from '../../registry/registrars/MimeTypeRegistrar';

export function useArchivePresets() {
    const registrar = MimeTypeRegistrar.getInstance();
    
    // Archive formats
    registrar.register({
        'zip': 'application/zip',
        'zipx': 'application/zip',
        'rar': 'application/vnd.rar',
        'r00': 'application/vnd.rn-realmedia',
        'r01': 'application/vnd.rn-realmedia',
        'r02': 'application/vnd.rn-realmedia',
        'r03': 'application/vnd.rn-realmedia',
        'r04': 'application/vnd.rn-realmedia',
        'r05': 'application/vnd.rn-realmedia',
        'r06': 'application/vnd.rn-realmedia',
        'r07': 'application/vnd.rn-realmedia',
        'r08': 'application/vnd.rn-realmedia',
        'r09': 'application/vnd.rn-realmedia',
        'r10': 'application/vnd.rn-realmedia',
        'r11': 'application/vnd.rn-realmedia',
        'r12': 'application/vnd.rn-realmedia',
        'r13': 'application/vnd.rn-realmedia',
        'r14': 'application/vnd.rn-realmedia',
        'r15': 'application/vnd.rn-realmedia',
        'r16': 'application/vnd.rn-realmedia',
        'r17': 'application/vnd.rn-realmedia',
        'r18': 'application/vnd.rn-realmedia',
        'r19': 'application/vnd.rn-realmedia',
        'r20': 'application/vnd.rn-realmedia',
        'r21': 'application/vnd.rn-realmedia',
        'r22': 'application/vnd.rn-realmedia',
        'r23': 'application/vnd.rn-realmedia',
        'r24': 'application/vnd.rn-realmedia',
        'r25': 'application/vnd.rn-realmedia',
        'r26': 'application/vnd.rn-realmedia',
        'r27': 'application/vnd.rn-realmedia',
        'r28': 'application/vnd.rn-realmedia',
        'r29': 'application/vnd.rn-realmedia',
        'r30': 'application/vnd.rn-realmedia',
        'r31': 'application/vnd.rn-realmedia',
        'r32': 'application/vnd.rn-realmedia',
        'r33': 'application/vnd.rn-realmedia',
        'r34': 'application/vnd.rn-realmedia',
        'r35': 'application/vnd.rn-realmedia',
        'r36': 'application/vnd.rn-realmedia',
        'r37': 'application/vnd.rn-realmedia',
        'r38': 'application/vnd.rn-realmedia',
        'r39': 'application/vnd.rn-realmedia',
        'r40': 'application/vnd.rn-realmedia',
        'r41': 'application/vnd.rn-realmedia',
        'r42': 'application/vnd.rn-realmedia',
        'r43': 'application/vnd.rn-realmedia',
        'r44': 'application/vnd.rn-realmedia',
        'r45': 'application/vnd.rn-realmedia',
        'r46': 'application/vnd.rn-realmedia',
        'r47': 'application/vnd.rn-realmedia',
        'r48': 'application/vnd.rn-realmedia',
        'r49': 'application/vnd.rn-realmedia',
        'r50': 'application/vnd.rn-realmedia',
        'r51': 'application/vnd.rn-realmedia',
        'r52': 'application/vnd.rn-realmedia',
        'r53': 'application/vnd.rn-realmedia',
        'r54': 'application/vnd.rn-realmedia',
        'r55': 'application/vnd.rn-realmedia',
        'r56': 'application/vnd.rn-realmedia',
        'r57': 'application/vnd.rn-realmedia',
        'r58': 'application/vnd.rn-realmedia',
        'r59': 'application/vnd.rn-realmedia',
        'r60': 'application/vnd.rn-realmedia',
        'r61': 'application/vnd.rn-realmedia',
        'r62': 'application/vnd.rn-realmedia',
        'r63': 'application/vnd.rn-realmedia',
        'r64': 'application/vnd.rn-realmedia',
        'r65': 'application/vnd.rn-realmedia',
        'r66': 'application/vnd.rn-realmedia',
        'r67': 'application/vnd.rn-realmedia',
        'r68': 'application/vnd.rn-realmedia',
        'r69': 'application/vnd.rn-realmedia',
        'r70': 'application/vnd.rn-realmedia',
        'r71': 'application/vnd.rn-realmedia',
        'r72': 'application/vnd.rn-realmedia',
        'r73': 'application/vnd.rn-realmedia',
        'r74': 'application/vnd.rn-realmedia',
        'r75': 'application/vnd.rn-realmedia',
        'r76': 'application/vnd.rn-realmedia',
        'r77': 'application/vnd.rn-realmedia',
        'r78': 'application/vnd.rn-realmedia',
        'r79': 'application/vnd.rn-realmedia',
        'r80': 'application/vnd.rn-realmedia',
        'r81': 'application/vnd.rn-realmedia',
        'r82': 'application/vnd.rn-realmedia',
        'r83': 'application/vnd.rn-realmedia',
        'r84': 'application/vnd.rn-realmedia',
        'r85': 'application/vnd.rn-realmedia',
        'r86': 'application/vnd.rn-realmedia',
        'r87': 'application/vnd.rn-realmedia',
        'r88': 'application/vnd.rn-realmedia',
        'r89': 'application/vnd.rn-realmedia',
        'r90': 'application/vnd.rn-realmedia',
        'r91': 'application/vnd.rn-realmedia',
        'r92': 'application/vnd.rn-realmedia',
        'r93': 'application/vnd.rn-realmedia',
        'r94': 'application/vnd.rn-realmedia',
        'r95': 'application/vnd.rn-realmedia',
        'r96': 'application/vnd.rn-realmedia',
        'r97': 'application/vnd.rn-realmedia',
        'r98': 'application/vnd.rn-realmedia',
        'r99': 'application/vnd.rn-realmedia',
        
        '7z': 'application/x-7z-compressed',
        's7z': 'application/x-7z-compressed',
        '7z.001': 'application/x-7z-compressed',
        
        'tar': 'application/x-tar',
        'gz': 'application/gzip',
        'tgz': 'application/x-compressed-tar',
        'tar.gz': 'application/x-compressed-tar',
        'tar.bz2': 'application/x-bzip-compressed-tar',
        'tar.xz': 'application/x-xz-compressed-tar',
        'tbz2': 'application/x-bzip-compressed-tar',
        'tbz': 'application/x-bzip-compressed-tar',
        'tlz': 'application/x-lzma-compressed-tar',
        'txz': 'application/x-xz-compressed-tar',
        'tzo': 'application/x-tzo',
        'lz': 'application/x-lzip',
        'lzma': 'application/x-lzma',
        'lzo': 'application/x-lzop',
        'xz': 'application/x-xz',
        
        'bz': 'application/x-bzip',
        'bz2': 'application/x-bzip2',
        'boz': 'application/x-bzip2',
        
        'z': 'application/x-compress',
        'z1': 'application/x-lzh-compressed',
        'z2': 'application/x-lzh-compressed',
        'z3': 'application/x-lzh-compressed',
        'z4': 'application/x-lzh-compressed',
        'z5': 'application/x-lzh-compressed',
        'z6': 'application/x-lzh-compressed',
        'z7': 'application/x-lzh-compressed',
        'z8': 'application/x-lzh-compressed',
        
        'deb': 'application/vnd.debian.binary-package',
        'rpm': 'application/x-redhat-package-manager',
        'pkg': 'application/octet-stream',
        'dmg': 'application/x-apple-diskimage',
        
        'cab': 'application/vnd.ms-cab-compressed',
        'lzh': 'application/x-lzh-compressed',
        'lha': 'application/x-lzh-compressed',
        'arj': 'application/x-arj',
        'zoo': 'application/octet-stream',
        'arc': 'application/x-freearc',
        'safariextz': 'application/x-safari-extension',
        
        'jar': 'application/java-archive',
        'war': 'application/java-archive',
        'sar': 'application/vnd.sbm.shorttext',
        'apk': 'application/vnd.android.package-archive',
        'hqx': 'application/mac-binhex40',
        'sit': 'application/x-stuffit',
        'sitx': 'application/x-stuffitx'
    });
}