/**
 * HTML 属性常量定义
 */

/** HTML 标准属性集合 */
export const HTML_PROPS_SET = new Set([
    // 通用属性
    'id',
    'class',
    'style',
    'title',
    'lang',
    'dir',
    'hidden',
    'tabindex',
    'accesskey',
    'contenteditable',
    'draggable',
    'spellcheck',
    'translate',
    // 表单属性
    'name',
    'value',
    'placeholder',
    'disabled',
    'readonly',
    'required',
    'checked',
    'selected',
    'multiple',
    'maxlength',
    'minlength',
    'pattern',
    'autocomplete',
    'autofocus',
    'form',
    'formaction',
    'formenctype',
    'formmethod',
    'formnovalidate',
    'formtarget',
    'list',
    'step',
    'min',
    'max',
    // 链接和图像属性
    'href',
    'target',
    'rel',
    'download',
    'src',
    'alt',
    'width',
    'height',
    'loading',
    'decoding',
    'srcset',
    'sizes',
    'usemap',
    'ismap',
    // 音视频属性
    'autoplay',
    'controls',
    'loop',
    'muted',
    'preload',
    'poster',
    'playsinline',
    // 其他
    'colspan',
    'rowspan',
    'headers',
    'scope',
    'datetime',
    'cite',
    'data',
    'label',
    'open',
    'reversed',
    'start',
    'wrap',
    'accept',
    'accept-charset',
    'action',
    'enctype',
    'method',
    'novalidate',
    'for',
    'span',
    'summary',
]);
