export enum KernelErrorCode {
    ENTITY_OPERATION_IN_PROGRESS = 'ENTITY_OPERATION_IN_PROGRESS',
    INVALID_PAGE_SIZE = 'INVALID_PAGE_SIZE',
    COMPOSABLE_NOT_FOUND = 'COMPOSABLE_NOT_FOUND',
    CIRCULAR_DEPENDENCY = 'CIRCULAR_DEPENDENCY',
    STREAM_REQUEST_FAILED = 'STREAM_REQUEST_FAILED',
    GESTURE_RECOGNITION_ERROR = 'GESTURE_RECOGNITION_ERROR',
    GESTURE_DISTANCE_INSUFFICIENT = 'GESTURE_DISTANCE_INSUFFICIENT',
    UNKNOWN_GESTURE_PROCESSOR = 'UNKNOWN_GESTURE_PROCESSOR',
}